
import os
import pickle
import datetime
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.auth.exceptions import RefreshError
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Scopes needed for uploading and playlist management
SCOPES = ['https://www.googleapis.com/auth/youtube']

def get_authenticated_service():
    """
    Authenticate with YouTube using OAuth 2.0.
    Requires 'client_secrets.json' to be present in the directory.
    """
    creds = None
    token_file = 'token.pickle'
    
    # Check if we have valid saved credentials
    if os.path.exists(token_file):
        print("Loading saved credentials...")
        with open(token_file, 'rb') as token:
            creds = pickle.load(token)
            
    # If no valid credentials, log in
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                print("Refreshing access token...")
                creds.refresh(Request())
            except RefreshError as e:
                print(f"Token refresh failed: {e}")
                print("Token has been revoked or expired. Deleting token and re-authenticating...")
                # Delete the invalid token file
                if os.path.exists(token_file):
                    os.remove(token_file)
                # Trigger new authentication flow
                creds = None
        
        if not creds:
            print("Starting new authentication flow...")
            client_secrets_file = 'client_secrets.json'
            if not os.path.exists(client_secrets_file):
                raise FileNotFoundError(f"Could not find {client_secrets_file}. You provided an API Key, but uploads require an OAuth 2.0 Client ID JSON file.")
                
            flow = InstalledAppFlow.from_client_secrets_file(
                client_secrets_file, SCOPES)
            creds = flow.run_local_server(port=0)
            
        # Save the credentials for the next run
        with open(token_file, 'wb') as token:
            pickle.dump(creds, token)
            
    return build('youtube', 'v3', credentials=creds)

def upload_video(file_path, title, description, category_id="22", keywords="quote,motivation"):
    """
    Uploads a video to YouTube.
    """
    if not os.path.exists(file_path):
        print(f"Error: Video file not found: {file_path}")
        return None

    youtube = get_authenticated_service()

    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': keywords.split(','),
            'categoryId': category_id
        },
        'status': {
            'privacyStatus': 'public', # Public so videos are immediately visible
            'selfDeclaredMadeForKids': False,
        }
    }

    print(f"Uploading {file_path}...")
    media = MediaFileUpload(file_path, chunksize=-1, resumable=True)
    
    request = youtube.videos().insert(
        part=','.join(body.keys()),
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Uploaded {int(status.progress() * 100)}%")

    print(f"Upload Complete! Video ID: {response['id']}")
    print(f"Link: https://youtu.be/{response['id']}")
    return response['id']

def add_video_to_playlist(video_id, playlist_id):
    """
    Adds a video to a specific playlist.
    """
    youtube = get_authenticated_service()
    
    print(f"Adding video {video_id} to playlist {playlist_id}...")
    request = youtube.playlistItems().insert(
        part="snippet",
        body={
            "snippet": {
                "playlistId": playlist_id,
                "resourceId": {
                    "kind": "youtube#video",
                    "videoId": video_id
                }
            }
        }
    )
    response = request.execute()
    print(f"Video added to playlist: {response['snippet']['title']}")

if __name__ == "__main__":
    # Test run
    # upload_video("daily_quote_video.mp4", "Test Quote Video", "Generated by Python")
    print("This module is intended to be imported.")
