name: Viral Courses Automation

on:
  schedule:
    - cron: '0 */8 * * *' # Run every 8 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: write # Needed to push changes to data.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install skia-python


      - name: Setup Credentials
        env:
          TOKEN_BASE64: ${{ secrets.VIRALCOURSESYOUTUBEKEY }}
        run: |
          if ($env:TOKEN_BASE64) {
            $bytes = [System.Convert]::FromBase64String($env:TOKEN_BASE64)
            [System.IO.File]::WriteAllBytes("token_viral_courses.pickle", $bytes)
            Write-Host "Token file created successfully."
          } else {
            Write-Error "VIRALCOURSESYOUTUBEKEY secret is missing!"
            exit 1
          }
        shell: powershell

      - name: Generate Video
        run: |
          python scripts/viralCourses/viral_courses_fast.py

      - name: Upload Video
        run: |
          python scripts/viralCourses/upload_viral_course.py

      - name: Pull latest changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git stash
          git pull --rebase origin main
          git stash pop || true
        shell: bash

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-remove uploaded viral course data"
          file_pattern: "data/viralCourses/data.json"
